export const GET_LOOKUP_FARM_TYPE = "GET_FARM_TYPE";
export const GET_LOOKUP_FARM_TYPE_SUCCESS = "GET_FARM_TYPE_SUCCESS";

export const GET_LOOKUP_SOIL_TYPE = "GET_LOOKUP_SOIL_TYPE"
export const GET_LOOKUP_SOIL_TYPE_SUCCESS = "GET_LOOKUP_SOIL_TYPE_SUCCESS"

export const GET_LOOKUP_CROP_TYPE = "GET_LOOKUP_CROP_TYPE"
export const GET_LOOKUP_CROP_TYPE_SUCCESS = "GET_LOOKUP_CROP_TYPE_SUCCESS"

export const GET_LOOKUP_VARIETY_TYPE = "GET_LOOKUP_VARIETY_TYPE"
export const GET_LOOKUP_VARIETY_TYPE_SUCCESS = "GET_LOOKUP_VARIETY_TYPE_SUCCESS"

export const GET_LOOKUP_YIELD_TYPE = "GET_LOOKUP_YIELD_TYPE"
export const GET_LOOKUP_YIELD_TYPE_SUCCESS = "GET_LOOKUP_YIELD_TYPE_SUCCESS"

export const GET_LOOKUP_IRRIGATION = "GET_LOOKUP_IRRIGATION"
export const GET_LOOKUP_IRRIGATION_SUCCESS = "GET_LOOKUP_IRRIGATION_SUCCESS"

export const GET_LOOKUP_MASTER_CROP = "GET_LOOKUP_MASTER_CROP"
export const GET_LOOKUP_MASTER_CROP_SUCCESS = "GET_LOOKUP_MASTER_CROP_SUCCESS"

export const LOOKUP_LOADING = "LOOKUP_LOADING";
export const LOOKUP_ERROR = "LOOKUP_ERROR"