export const ADD_MASTER_CROP = "ADD_MASTER_CROP"
export const ADD_MASTER_CROP_SUCCESS = "ADD_MASTER_CROP_SUCCESS";

export const EDIT_MASTER_CROP = "EDIT_MASTER_CROP"
export const EDIT_MASTER_CROP_SUCCESS = "EDIT_MASTER_CROP_SUCCESS"

export const DELETE_MASTER_CROP = "EDIT_MASTER_CROP"
export const DELETE_MASTER_CROP_SUCCESS = "EDIT_MASTER_CROP_SUCCESS"

export const GET_MASTER_CROP = "GET_MASTER_CROP"
export const GET_MASTER_CROP_SUCCESS = "GET_MASTER_CROP_SUCCESS"