export const ADD_MASTER_CROP = "ADD_MASTER_CROP";
export const NEXT_MASTER_CROP_PAGE = "NEXT_MASTER_CROP_PAGE";
export const PREV_MASTER_CROP_PAGE = "PREV_MASTER_CROP_PAGE";
export const ADD_MASTER_CROP_SUCCESS = "ADD_MASTER_CROP_SUCCESS";

export const EDIT_MASTER_CROP = "EDIT_MASTER_CROP"
export const EDIT_MASTER_CROP_SUCCESS = "EDIT_MASTER_CROP_SUCCESS"

export const DELETE_MASTER_CROP = "DELETE_MASTER_CROP"
export const DELETE_MASTER_CROP_SUCCESS = "DELETE_MASTER_CROP_SUCCESS"

export const GET_MASTER_CROP = "GET_MASTER_CROP"
export const GET_MASTER_CROP_SUCCESS = "GET_MASTER_CROP_SUCCESS"


export const EDIT_MASTER_CROP_FORM = "EDIT_MASTER_CROP_FORM";
export const ADD_MASTER_CROP_FROM = "ADD_MASTER_CROP_FROM";
export const CLOSE_MASTER_CROP_MODAL = "CLOSE_ADD_EDIT_MASTER_CROP_MODAL";