export const ADD_CROP_TYPE = "ADD_CROP_TYPE";
export const NEXT_CROP_TYPE_PAGE = "NEXT_CROP_TYPE_PAGE";
export const PREV_CROP_TYPE_PAGE = "PREV_CROP_TYPE_PAGE";
export const ADD_CROP_TYPE_SUCCESS = "ADD_CROP_TYPE_SUCCESS";

export const EDIT_CROP_TYPE = "EDIT_CROP_TYPE"
export const EDIT_CROP_TYPE_SUCCESS = "EDIT_CROP_TYPE_SUCCESS"

export const DELETE_CROP_TYPE = "DELETE_CROP_TYPE"
export const DELETE_CROP_TYPE_SUCCESS = "DELETE_CROP_TYPE_SUCCESS"

export const GET_CROP_TYPE = "GET_CROP_TYPE"
export const GET_CROP_TYPE_SUCCESS = "GET_CROP_TYPE_SUCCESS"


export const EDIT_CROP_TYPE_FORM = "EDIT_CROP_TYPE_FORM";
export const ADD_CROP_TYPE_FROM = "ADD_CROP_TYPE_FROM";
export const CLOSE_CROP_TYPE_MODAL = "CLOSE_ADD_EDIT_CROP_TYPE_MODAL";